-- 0040_seed_route_permissions: seed every permission the route table guards.
--
-- api.go's header flags this as a ship blocker: any permission referenced by
-- apiRoutes but absent from 0007_rbac makes granted() deny the request for
-- every principal, admin included. The visible symptom is a deferred route
-- answering 403 "missing permission: X" instead of its honest 501, and a
-- dashboard whose pages all look broken.
--
-- The grant targets whichever roles are flagged is_admin, resolved from the
-- roles table instead of a hardcoded name: 0024_two_roles collapses the role
-- model to exactly admin + member and deletes every other role, so naming
-- 'owner' here would violate role_permissions_role_id_fkey.

INSERT INTO permissions (id, name, description) VALUES
    ('admin.read', 'Read admin', 'Referenced by the Porter route table'),
    ('aiagent.create', 'Create aiagent', 'Referenced by the Porter route table'),
    ('aiagent.delete', 'Delete aiagent', 'Referenced by the Porter route table'),
    ('aiagent.list', 'List aiagent', 'Referenced by the Porter route table'),
    ('aiagent.update', 'Update aiagent', 'Referenced by the Porter route table'),
    ('aiplan.approve', 'Approve aiplan', 'Referenced by the Porter route table'),
    ('aiplan.create', 'Create aiplan', 'Referenced by the Porter route table'),
    ('aiplan.list', 'List aiplan', 'Referenced by the Porter route table'),
    ('alertroute.list', 'List alertroute', 'Referenced by the Porter route table'),
    ('alertroute.update', 'Update alertroute', 'Referenced by the Porter route table'),
    ('audit.export', 'Export audit', 'Referenced by the Porter route table'),
    ('audit.read', 'Read audit', 'Referenced by the Porter route table'),
    ('backup.create', 'Create backup', 'Referenced by the Porter route table'),
    ('backup.delete', 'Delete backup', 'Referenced by the Porter route table'),
    ('backup.list', 'List backup', 'Referenced by the Porter route table'),
    ('backup.read', 'Read backup', 'Referenced by the Porter route table'),
    ('backup.restore', 'Restore backup', 'Referenced by the Porter route table'),
    ('backuppolicy.create', 'Create backuppolicy', 'Referenced by the Porter route table'),
    ('backuppolicy.delete', 'Delete backuppolicy', 'Referenced by the Porter route table'),
    ('backuppolicy.list', 'List backuppolicy', 'Referenced by the Porter route table'),
    ('backuppolicy.update', 'Update backuppolicy', 'Referenced by the Porter route table'),
    ('billing.manage', 'Manage billing', 'Referenced by the Porter route table'),
    ('billing.read', 'Read billing', 'Referenced by the Porter route table'),
    ('bucket.create', 'Create bucket', 'Referenced by the Porter route table'),
    ('bucket.delete', 'Delete bucket', 'Referenced by the Porter route table'),
    ('bucket.list', 'List bucket', 'Referenced by the Porter route table'),
    ('build.cancel', 'Cancel build', 'Referenced by the Porter route table'),
    ('build.list', 'List build', 'Referenced by the Porter route table'),
    ('certificate.create', 'Create certificate', 'Referenced by the Porter route table'),
    ('certificate.delete', 'Delete certificate', 'Referenced by the Porter route table'),
    ('certificate.issue', 'Issue certificate', 'Referenced by the Porter route table'),
    ('certificate.list', 'List certificate', 'Referenced by the Porter route table'),
    ('certificate.renew', 'Renew certificate', 'Referenced by the Porter route table'),
    ('certificate.revoke', 'Revoke certificate', 'Referenced by the Porter route table'),
    ('certificate.update', 'Update certificate', 'Referenced by the Porter route table'),
    ('cf.dns', 'Dns cf', 'Referenced by the Porter route table'),
    ('cf.tunnel', 'Tunnel cf', 'Referenced by the Porter route table'),
    ('credit.create', 'Create credit', 'Referenced by the Porter route table'),
    ('credit.list', 'List credit', 'Referenced by the Porter route table'),
    ('customer.create', 'Create customer', 'Referenced by the Porter route table'),
    ('customer.delete', 'Delete customer', 'Referenced by the Porter route table'),
    ('customer.list', 'List customer', 'Referenced by the Porter route table'),
    ('customer.update', 'Update customer', 'Referenced by the Porter route table'),
    ('database.create', 'Create database', 'Referenced by the Porter route table'),
    ('database.delete', 'Delete database', 'Referenced by the Porter route table'),
    ('database.list', 'List database', 'Referenced by the Porter route table'),
    ('database.update', 'Update database', 'Referenced by the Porter route table'),
    ('deployment.freeze', 'Freeze deployment', 'Referenced by the Porter route table'),
    ('destination.create', 'Create destination', 'Referenced by the Porter route table'),
    ('destination.delete', 'Delete destination', 'Referenced by the Porter route table'),
    ('destination.list', 'List destination', 'Referenced by the Porter route table'),
    ('destination.update', 'Update destination', 'Referenced by the Porter route table'),
    ('dnsrecord.create', 'Create dnsrecord', 'Referenced by the Porter route table'),
    ('dnsrecord.delete', 'Delete dnsrecord', 'Referenced by the Porter route table'),
    ('dnsrecord.list', 'List dnsrecord', 'Referenced by the Porter route table'),
    ('dnsrecord.update', 'Update dnsrecord', 'Referenced by the Porter route table'),
    ('dnszone.create', 'Create dnszone', 'Referenced by the Porter route table'),
    ('dnszone.delete', 'Delete dnszone', 'Referenced by the Porter route table'),
    ('dnszone.list', 'List dnszone', 'Referenced by the Porter route table'),
    ('dnszone.update', 'Update dnszone', 'Referenced by the Porter route table'),
    ('dnszone.verify', 'Verify dnszone', 'Referenced by the Porter route table'),
    ('dunning.list', 'List dunning', 'Referenced by the Porter route table'),
    ('dunning.manage', 'Manage dunning', 'Referenced by the Porter route table'),
    ('email.manage', 'Manage email', 'Referenced by the Porter route table'),
    ('email.send', 'Send email', 'Referenced by the Porter route table'),
    ('entitlement.create', 'Create entitlement', 'Referenced by the Porter route table'),
    ('entitlement.delete', 'Delete entitlement', 'Referenced by the Porter route table'),
    ('entitlement.list', 'List entitlement', 'Referenced by the Porter route table'),
    ('extension.create', 'Create extension', 'Referenced by the Porter route table'),
    ('extension.delete', 'Delete extension', 'Referenced by the Porter route table'),
    ('extension.list', 'List extension', 'Referenced by the Porter route table'),
    ('extension.update', 'Update extension', 'Referenced by the Porter route table'),
    ('gateway.create', 'Create gateway', 'Referenced by the Porter route table'),
    ('gateway.delete', 'Delete gateway', 'Referenced by the Porter route table'),
    ('gateway.list', 'List gateway', 'Referenced by the Porter route table'),
    ('gateway.update', 'Update gateway', 'Referenced by the Porter route table'),
    ('group.read', 'Read group', 'Referenced by the Porter route table'),
    ('image.sbom', 'Sbom image', 'Referenced by the Porter route table'),
    ('image.scan', 'Scan image', 'Referenced by the Porter route table'),
    ('image.sign', 'Sign image', 'Referenced by the Porter route table'),
    ('image.upload', 'Upload image', 'Referenced by the Porter route table'),
    ('incident.delete', 'Delete incident', 'Referenced by the Porter route table'),
    ('incident.list', 'List incident', 'Referenced by the Porter route table'),
    ('incident.update', 'Update incident', 'Referenced by the Porter route table'),
    ('invoice.list', 'List invoice', 'Referenced by the Porter route table'),
    ('invoice.manage', 'Manage invoice', 'Referenced by the Porter route table'),
    ('k8s.agent.delete', 'Delete k8s.agent', 'Referenced by the Porter route table'),
    ('k8s.agent.list', 'List k8s.agent', 'Referenced by the Porter route table'),
    ('k8s.cluster.adopt', 'Adopt k8s.cluster', 'Referenced by the Porter route table'),
    ('k8s.cluster.create', 'Create k8s.cluster', 'Referenced by the Porter route table'),
    ('k8s.cluster.delete', 'Delete k8s.cluster', 'Referenced by the Porter route table'),
    ('k8s.cluster.exec', 'Exec k8s.cluster', 'Referenced by the Porter route table'),
    ('k8s.cluster.list', 'List k8s.cluster', 'Referenced by the Porter route table'),
    ('k8s.cluster.read', 'Read k8s.cluster', 'Referenced by the Porter route table'),
    ('k8s.cluster.update', 'Update k8s.cluster', 'Referenced by the Porter route table'),
    ('kernel.build', 'Build kernel', 'Referenced by the Porter route table'),
    ('lb.create', 'Create lb', 'Referenced by the Porter route table'),
    ('lb.delete', 'Delete lb', 'Referenced by the Porter route table'),
    ('lb.list', 'List lb', 'Referenced by the Porter route table'),
    ('lb.update', 'Update lb', 'Referenced by the Porter route table'),
    ('maintenance.create', 'Create maintenance', 'Referenced by the Porter route table'),
    ('maintenance.delete', 'Delete maintenance', 'Referenced by the Porter route table'),
    ('maintenance.list', 'List maintenance', 'Referenced by the Porter route table'),
    ('maintenance.update', 'Update maintenance', 'Referenced by the Porter route table'),
    ('marketplace.install', 'Install marketplace', 'Referenced by the Porter route table'),
    ('marketplace.list', 'List marketplace', 'Referenced by the Porter route table'),
    ('mcp.call', 'Call mcp', 'Referenced by the Porter route table'),
    ('mcp.describe', 'Describe mcp', 'Referenced by the Porter route table'),
    ('mcp.search', 'Search mcp', 'Referenced by the Porter route table'),
    ('node.cordon', 'Cordon node', 'Referenced by the Porter route table'),
    ('node.drain', 'Drain node', 'Referenced by the Porter route table'),
    ('node.maintenance', 'Maintenance node', 'Referenced by the Porter route table'),
    ('node.recover', 'Recover node', 'Referenced by the Porter route table'),
    ('node.replace', 'Replace node', 'Referenced by the Porter route table'),
    ('node.upgrade', 'Upgrade node', 'Referenced by the Porter route table'),
    ('nodepool.create', 'Create nodepool', 'Referenced by the Porter route table'),
    ('nodepool.delete', 'Delete nodepool', 'Referenced by the Porter route table'),
    ('nodepool.list', 'List nodepool', 'Referenced by the Porter route table'),
    ('nodepool.update', 'Update nodepool', 'Referenced by the Porter route table'),
    ('notification.list', 'List notification', 'Referenced by the Porter route table'),
    ('notification.update', 'Update notification', 'Referenced by the Porter route table'),
    ('objectstore.create', 'Create objectstore', 'Referenced by the Porter route table'),
    ('objectstore.delete', 'Delete objectstore', 'Referenced by the Porter route table'),
    ('objectstore.list', 'List objectstore', 'Referenced by the Porter route table'),
    ('objectstore.update', 'Update objectstore', 'Referenced by the Porter route table'),
    ('onboarding.read', 'Read onboarding', 'Referenced by the Porter route table'),
    ('org.create', 'Create org', 'Referenced by the Porter route table'),
    ('org.delete', 'Delete org', 'Referenced by the Porter route table'),
    ('payment.list', 'List payment', 'Referenced by the Porter route table'),
    ('payment.manage', 'Manage payment', 'Referenced by the Porter route table'),
    ('payment.refund', 'Refund payment', 'Referenced by the Porter route table'),
    ('portforward.create', 'Create portforward', 'Referenced by the Porter route table'),
    ('portforward.delete', 'Delete portforward', 'Referenced by the Porter route table'),
    ('portforward.list', 'List portforward', 'Referenced by the Porter route table'),
    ('price.create', 'Create price', 'Referenced by the Porter route table'),
    ('price.delete', 'Delete price', 'Referenced by the Porter route table'),
    ('price.list', 'List price', 'Referenced by the Porter route table'),
    ('price.update', 'Update price', 'Referenced by the Porter route table'),
    ('product.create', 'Create product', 'Referenced by the Porter route table'),
    ('product.delete', 'Delete product', 'Referenced by the Porter route table'),
    ('product.list', 'List product', 'Referenced by the Porter route table'),
    ('product.update', 'Update product', 'Referenced by the Porter route table'),
    ('project.write', 'Write project', 'Referenced by the Porter route table'),
    ('provider.create', 'Create provider', 'Referenced by the Porter route table'),
    ('provider.delete', 'Delete provider', 'Referenced by the Porter route table'),
    ('provider.list', 'List provider', 'Referenced by the Porter route table'),
    ('provider.update', 'Update provider', 'Referenced by the Porter route table'),
    ('refund.list', 'List refund', 'Referenced by the Porter route table'),
    ('region.create', 'Create region', 'Referenced by the Porter route table'),
    ('region.delete', 'Delete region', 'Referenced by the Porter route table'),
    ('region.list', 'List region', 'Referenced by the Porter route table'),
    ('region.update', 'Update region', 'Referenced by the Porter route table'),
    ('registry.create', 'Create registry', 'Referenced by the Porter route table'),
    ('registry.delete', 'Delete registry', 'Referenced by the Porter route table'),
    ('registry.list', 'List registry', 'Referenced by the Porter route table'),
    ('registry.update', 'Update registry', 'Referenced by the Porter route table'),
    ('replica.pause', 'Pause replica', 'Referenced by the Porter route table'),
    ('replica.reboot', 'Reboot replica', 'Referenced by the Porter route table'),
    ('replica.restore', 'Restore replica', 'Referenced by the Porter route table'),
    ('replica.resume', 'Resume replica', 'Referenced by the Porter route table'),
    ('replica.snapshot', 'Snapshot replica', 'Referenced by the Porter route table'),
    ('reseller.create', 'Create reseller', 'Referenced by the Porter route table'),
    ('reseller.delete', 'Delete reseller', 'Referenced by the Porter route table'),
    ('reseller.list', 'List reseller', 'Referenced by the Porter route table'),
    ('reseller.update', 'Update reseller', 'Referenced by the Porter route table'),
    ('route.create', 'Create route', 'Referenced by the Porter route table'),
    ('route.delete', 'Delete route', 'Referenced by the Porter route table'),
    ('route.list', 'List route', 'Referenced by the Porter route table'),
    ('route.update', 'Update route', 'Referenced by the Porter route table'),
    ('s3storage.create', 'Create s3storage', 'Referenced by the Porter route table'),
    ('s3storage.delete', 'Delete s3storage', 'Referenced by the Porter route table'),
    ('s3storage.list', 'List s3storage', 'Referenced by the Porter route table'),
    ('s3storage.update', 'Update s3storage', 'Referenced by the Porter route table'),
    ('secret.rotate', 'Rotate secret', 'Referenced by the Porter route table'),
    ('security.apitoken.create', 'Create security.apitoken', 'Referenced by the Porter route table'),
    ('security.apitoken.delete', 'Delete security.apitoken', 'Referenced by the Porter route table'),
    ('security.apitoken.list', 'List security.apitoken', 'Referenced by the Porter route table'),
    ('security.cloudinit.create', 'Create security.cloudinit', 'Referenced by the Porter route table'),
    ('security.cloudinit.delete', 'Delete security.cloudinit', 'Referenced by the Porter route table'),
    ('security.cloudinit.list', 'List security.cloudinit', 'Referenced by the Porter route table'),
    ('security.cloudinit.update', 'Update security.cloudinit', 'Referenced by the Porter route table'),
    ('security.cloudtoken.create', 'Create security.cloudtoken', 'Referenced by the Porter route table'),
    ('security.cloudtoken.delete', 'Delete security.cloudtoken', 'Referenced by the Porter route table'),
    ('security.cloudtoken.list', 'List security.cloudtoken', 'Referenced by the Porter route table'),
    ('security.cloudtoken.update', 'Update security.cloudtoken', 'Referenced by the Porter route table'),
    ('security.integration.create', 'Create security.integration', 'Referenced by the Porter route table'),
    ('security.integration.delete', 'Delete security.integration', 'Referenced by the Porter route table'),
    ('security.integration.list', 'List security.integration', 'Referenced by the Porter route table'),
    ('security.privatekey.create', 'Create security.privatekey', 'Referenced by the Porter route table'),
    ('security.privatekey.delete', 'Delete security.privatekey', 'Referenced by the Porter route table'),
    ('security.privatekey.list', 'List security.privatekey', 'Referenced by the Porter route table'),
    ('serviceaccount.create', 'Create serviceaccount', 'Referenced by the Porter route table'),
    ('serviceaccount.delete', 'Delete serviceaccount', 'Referenced by the Porter route table'),
    ('serviceaccount.list', 'List serviceaccount', 'Referenced by the Porter route table'),
    ('serviceaccount.update', 'Update serviceaccount', 'Referenced by the Porter route table'),
    ('settings.list', 'List settings', 'Referenced by the Porter route table'),
    ('settings.update', 'Update settings', 'Referenced by the Porter route table'),
    ('share.create', 'Create share', 'Referenced by the Porter route table'),
    ('share.delete', 'Delete share', 'Referenced by the Porter route table'),
    ('silence.create', 'Create silence', 'Referenced by the Porter route table'),
    ('silence.delete', 'Delete silence', 'Referenced by the Porter route table'),
    ('silence.list', 'List silence', 'Referenced by the Porter route table'),
    ('slo.create', 'Create slo', 'Referenced by the Porter route table'),
    ('slo.delete', 'Delete slo', 'Referenced by the Porter route table'),
    ('slo.list', 'List slo', 'Referenced by the Porter route table'),
    ('slo.update', 'Update slo', 'Referenced by the Porter route table'),
    ('snapshot.create', 'Create snapshot', 'Referenced by the Porter route table'),
    ('snapshot.delete', 'Delete snapshot', 'Referenced by the Porter route table'),
    ('snapshot.list', 'List snapshot', 'Referenced by the Porter route table'),
    ('source.delete', 'Delete source', 'Referenced by the Porter route table'),
    ('source.list', 'List source', 'Referenced by the Porter route table'),
    ('storage.create', 'Create storage', 'Referenced by the Porter route table'),
    ('storage.delete', 'Delete storage', 'Referenced by the Porter route table'),
    ('storage.list', 'List storage', 'Referenced by the Porter route table'),
    ('storage.update', 'Update storage', 'Referenced by the Porter route table'),
    ('storageclass.create', 'Create storageclass', 'Referenced by the Porter route table'),
    ('storageclass.delete', 'Delete storageclass', 'Referenced by the Porter route table'),
    ('storageclass.list', 'List storageclass', 'Referenced by the Porter route table'),
    ('storageclass.update', 'Update storageclass', 'Referenced by the Porter route table'),
    ('subscription.list', 'List subscription', 'Referenced by the Porter route table'),
    ('subscription.manage', 'Manage subscription', 'Referenced by the Porter route table'),
    ('support.impersonate', 'Impersonate support', 'Referenced by the Porter route table'),
    ('synthetic.create', 'Create synthetic', 'Referenced by the Porter route table'),
    ('synthetic.delete', 'Delete synthetic', 'Referenced by the Porter route table'),
    ('synthetic.list', 'List synthetic', 'Referenced by the Porter route table'),
    ('synthetic.run', 'Run synthetic', 'Referenced by the Porter route table'),
    ('synthetic.update', 'Update synthetic', 'Referenced by the Porter route table'),
    ('tax.list', 'List tax', 'Referenced by the Porter route table'),
    ('tax.manage', 'Manage tax', 'Referenced by the Porter route table'),
    ('template.manage', 'Manage template', 'Referenced by the Porter route table'),
    ('template.read', 'Read template', 'Referenced by the Porter route table'),
    ('trace.read', 'Read trace', 'Referenced by the Porter route table'),
    ('usage.read', 'Read usage', 'Referenced by the Porter route table'),
    ('vm.migrate', 'Migrate vm', 'Referenced by the Porter route table'),
    ('webhook.create', 'Create webhook', 'Referenced by the Porter route table'),
    ('webhook.delete', 'Delete webhook', 'Referenced by the Porter route table'),
    ('webhook.list', 'List webhook', 'Referenced by the Porter route table'),
    ('webhook.update', 'Update webhook', 'Referenced by the Porter route table'),
    ('workflow.create', 'Create workflow', 'Referenced by the Porter route table'),
    ('workflow.delete', 'Delete workflow', 'Referenced by the Porter route table'),
    ('workflow.list', 'List workflow', 'Referenced by the Porter route table'),
    ('workflow.run', 'Run workflow', 'Referenced by the Porter route table'),
    ('workflow.update', 'Update workflow', 'Referenced by the Porter route table'),
    ('zone.create', 'Create zone', 'Referenced by the Porter route table'),
    ('zone.delete', 'Delete zone', 'Referenced by the Porter route table'),
    ('zone.list', 'List zone', 'Referenced by the Porter route table'),
    ('zone.update', 'Update zone', 'Referenced by the Porter route table')
ON CONFLICT (id) DO NOTHING;

-- Attach the new codes to the platform admin role(s), idempotently.
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, v.permission_id
FROM (VALUES
    ('admin.read'),
    ('aiagent.create'),
    ('aiagent.delete'),
    ('aiagent.list'),
    ('aiagent.update'),
    ('aiplan.approve'),
    ('aiplan.create'),
    ('aiplan.list'),
    ('alertroute.list'),
    ('alertroute.update'),
    ('audit.export'),
    ('audit.read'),
    ('backup.create'),
    ('backup.delete'),
    ('backup.list'),
    ('backup.read'),
    ('backup.restore'),
    ('backuppolicy.create'),
    ('backuppolicy.delete'),
    ('backuppolicy.list'),
    ('backuppolicy.update'),
    ('billing.manage'),
    ('billing.read'),
    ('bucket.create'),
    ('bucket.delete'),
    ('bucket.list'),
    ('build.cancel'),
    ('build.list'),
    ('certificate.create'),
    ('certificate.delete'),
    ('certificate.issue'),
    ('certificate.list'),
    ('certificate.renew'),
    ('certificate.revoke'),
    ('certificate.update'),
    ('cf.dns'),
    ('cf.tunnel'),
    ('credit.create'),
    ('credit.list'),
    ('customer.create'),
    ('customer.delete'),
    ('customer.list'),
    ('customer.update'),
    ('database.create'),
    ('database.delete'),
    ('database.list'),
    ('database.update'),
    ('deployment.freeze'),
    ('destination.create'),
    ('destination.delete'),
    ('destination.list'),
    ('destination.update'),
    ('dnsrecord.create'),
    ('dnsrecord.delete'),
    ('dnsrecord.list'),
    ('dnsrecord.update'),
    ('dnszone.create'),
    ('dnszone.delete'),
    ('dnszone.list'),
    ('dnszone.update'),
    ('dnszone.verify'),
    ('dunning.list'),
    ('dunning.manage'),
    ('email.manage'),
    ('email.send'),
    ('entitlement.create'),
    ('entitlement.delete'),
    ('entitlement.list'),
    ('extension.create'),
    ('extension.delete'),
    ('extension.list'),
    ('extension.update'),
    ('gateway.create'),
    ('gateway.delete'),
    ('gateway.list'),
    ('gateway.update'),
    ('group.read'),
    ('image.sbom'),
    ('image.scan'),
    ('image.sign'),
    ('image.upload'),
    ('incident.delete'),
    ('incident.list'),
    ('incident.update'),
    ('invoice.list'),
    ('invoice.manage'),
    ('k8s.agent.delete'),
    ('k8s.agent.list'),
    ('k8s.cluster.adopt'),
    ('k8s.cluster.create'),
    ('k8s.cluster.delete'),
    ('k8s.cluster.exec'),
    ('k8s.cluster.list'),
    ('k8s.cluster.read'),
    ('k8s.cluster.update'),
    ('kernel.build'),
    ('lb.create'),
    ('lb.delete'),
    ('lb.list'),
    ('lb.update'),
    ('maintenance.create'),
    ('maintenance.delete'),
    ('maintenance.list'),
    ('maintenance.update'),
    ('marketplace.install'),
    ('marketplace.list'),
    ('mcp.call'),
    ('mcp.describe'),
    ('mcp.search'),
    ('node.cordon'),
    ('node.drain'),
    ('node.maintenance'),
    ('node.recover'),
    ('node.replace'),
    ('node.upgrade'),
    ('nodepool.create'),
    ('nodepool.delete'),
    ('nodepool.list'),
    ('nodepool.update'),
    ('notification.list'),
    ('notification.update'),
    ('objectstore.create'),
    ('objectstore.delete'),
    ('objectstore.list'),
    ('objectstore.update'),
    ('onboarding.read'),
    ('org.create'),
    ('org.delete'),
    ('payment.list'),
    ('payment.manage'),
    ('payment.refund'),
    ('portforward.create'),
    ('portforward.delete'),
    ('portforward.list'),
    ('price.create'),
    ('price.delete'),
    ('price.list'),
    ('price.update'),
    ('product.create'),
    ('product.delete'),
    ('product.list'),
    ('product.update'),
    ('project.write'),
    ('provider.create'),
    ('provider.delete'),
    ('provider.list'),
    ('provider.update'),
    ('refund.list'),
    ('region.create'),
    ('region.delete'),
    ('region.list'),
    ('region.update'),
    ('registry.create'),
    ('registry.delete'),
    ('registry.list'),
    ('registry.update'),
    ('replica.pause'),
    ('replica.reboot'),
    ('replica.restore'),
    ('replica.resume'),
    ('replica.snapshot'),
    ('reseller.create'),
    ('reseller.delete'),
    ('reseller.list'),
    ('reseller.update'),
    ('route.create'),
    ('route.delete'),
    ('route.list'),
    ('route.update'),
    ('s3storage.create'),
    ('s3storage.delete'),
    ('s3storage.list'),
    ('s3storage.update'),
    ('secret.rotate'),
    ('security.apitoken.create'),
    ('security.apitoken.delete'),
    ('security.apitoken.list'),
    ('security.cloudinit.create'),
    ('security.cloudinit.delete'),
    ('security.cloudinit.list'),
    ('security.cloudinit.update'),
    ('security.cloudtoken.create'),
    ('security.cloudtoken.delete'),
    ('security.cloudtoken.list'),
    ('security.cloudtoken.update'),
    ('security.integration.create'),
    ('security.integration.delete'),
    ('security.integration.list'),
    ('security.privatekey.create'),
    ('security.privatekey.delete'),
    ('security.privatekey.list'),
    ('serviceaccount.create'),
    ('serviceaccount.delete'),
    ('serviceaccount.list'),
    ('serviceaccount.update'),
    ('settings.list'),
    ('settings.update'),
    ('share.create'),
    ('share.delete'),
    ('silence.create'),
    ('silence.delete'),
    ('silence.list'),
    ('slo.create'),
    ('slo.delete'),
    ('slo.list'),
    ('slo.update'),
    ('snapshot.create'),
    ('snapshot.delete'),
    ('snapshot.list'),
    ('source.delete'),
    ('source.list'),
    ('storage.create'),
    ('storage.delete'),
    ('storage.list'),
    ('storage.update'),
    ('storageclass.create'),
    ('storageclass.delete'),
    ('storageclass.list'),
    ('storageclass.update'),
    ('subscription.list'),
    ('subscription.manage'),
    ('support.impersonate'),
    ('synthetic.create'),
    ('synthetic.delete'),
    ('synthetic.list'),
    ('synthetic.run'),
    ('synthetic.update'),
    ('tax.list'),
    ('tax.manage'),
    ('template.manage'),
    ('template.read'),
    ('trace.read'),
    ('usage.read'),
    ('vm.migrate'),
    ('webhook.create'),
    ('webhook.delete'),
    ('webhook.list'),
    ('webhook.update'),
    ('workflow.create'),
    ('workflow.delete'),
    ('workflow.list'),
    ('workflow.run'),
    ('workflow.update'),
    ('zone.create'),
    ('zone.delete'),
    ('zone.list'),
    ('zone.update')
) AS v(permission_id)
CROSS JOIN roles r
WHERE r.is_admin = true
  AND NOT EXISTS (
      SELECT 1 FROM role_permissions rp
      WHERE rp.role_id = r.id AND rp.permission_id = v.permission_id
  );
