// Package guestsetup generates first-boot guest content (PVE-16, PVE-17,
// PVE-18, OCM-28): an idempotent setup script (static-aware DHCP skip,
// nocloud datasource on /dev/vdb, stamp-guard), a minimal PID1 for
// systemd-less images, AI-template volume specs (immutable root + detached
// models volume), and the guest supervision/pin convention (sv/ dirs +
// versions.json). Output is data the build pipeline installs into the
// rootfs before mkfs — never executed on the host.
package guestsetup

import (
	"fmt"
	"strings"
)

// Profile selects how much userspace the setup installs.
type Profile string

const (
	ProfileMinimal  Profile = "minimal"  // microvm-init shell only
	ProfileStandard Profile = "standard" // SSH + cloud-init + agent + networkd (default)
	ProfileFull     Profile = "full"     // standard + container runtime
)

// StampPath marks a completed first boot so reruns are no-ops.
const StampPath = "/etc/porter-setup-done"

// NoDockerPath opts the VM out of container-runtime install.
const NoDockerPath = "/etc/porter-no-docker"

// SetupOptions tunes the generated setup script.
type SetupOptions struct {
	Profile    Profile
	StaticCIDR string // non-empty: skip DHCP, write static net (validated upstream)
	DNS        []string
	EnableSSH  bool
	UseNocloud bool // mount /dev/vdb as cidata nocloud datasource
}

// SetupScript renders an idempotent first-boot script. It is stamp-guarded
// (exits 0 when StampPath exists) and skips DHCP when static config or
// cloud-init/networkd static files are already present.
func SetupScript(o SetupOptions) string {
	var b strings.Builder
	b.WriteString("#!/bin/sh\n# generated by porter guestsetup: idempotent first boot\n")
	b.WriteString(fmt.Sprintf("[ -f %s ] && exit 0\n", StampPath))
	if o.StaticCIDR != "" {
		b.WriteString("# static config present: DHCP skipped\n")
		b.WriteString(fmt.Sprintf("echo %q > /etc/porter-static-net\n", o.StaticCIDR))
	} else {
		b.WriteString("if [ ! -f /etc/porter-static-net ] && [ ! -f /etc/cloud/cloud.cfg.d/* ] 2>/dev/null; then\n")
		b.WriteString("  (command -v dhclient >/dev/null && dhclient -4 eth0) || (command -v udhcpc >/dev/null && udhcpc -i eth0) || true\n")
		b.WriteString("fi\n")
	}
	if len(o.DNS) > 0 {
		b.WriteString(fmt.Sprintf("printf 'nameserver %s\\n' %s > /etc/resolv.conf\n",
			strings.Join(o.DNS, "\\nnameserver "), ""))
	}
	if o.UseNocloud {
		b.WriteString("mkdir -p /mnt/cidata && mount -o ro /dev/vdb /mnt/cidata 2>/dev/null || true\n")
	}
	if o.EnableSSH {
		b.WriteString("command -v sshd >/dev/null && mkdir -p /run/sshd\n")
	}
	if o.Profile == ProfileFull {
		b.WriteString(fmt.Sprintf("[ -f %s ] || (command -v dockerd >/dev/null && dockerd >/var/log/dockerd.log 2>&1 &)\n", NoDockerPath))
	}
	b.WriteString(fmt.Sprintf("touch %s\n", StampPath))
	return b.String()
}

// MinInit renders a minimal PID1 for images without systemd (PVE-17): mounts
// pseudo-filesystems, brings up lo, tries DHCP on the first ethernet unless
// static config exists, then execs the workload command.
func MinInit(cmd []string) string {
	quoted := make([]string, 0, len(cmd))
	for _, a := range cmd {
		quoted = append(quoted, "'"+strings.ReplaceAll(a, "'", `'\''`)+"'")
	}
	return `#!/bin/sh
# generated by porter guestsetup: minimal PID1
mount -t proc proc /proc 2>/dev/null
mount -t sysfs sys /sys 2>/dev/null
mount -t devtmpfs dev /dev 2>/dev/null
ip link set lo up 2>/dev/null
if [ ! -f /etc/porter-static-net ]; then
  (command -v dhclient >/dev/null && dhclient -4 eth0) || (command -v udhcpc >/dev/null && udhcpc -i eth0) || true
fi
exec ` + strings.Join(quoted, " ") + "\n"
}

// AIModelsLabel is the filesystem label for the detached models volume.
const AIModelsLabel = "porter-models"

// AITemplate describes the AI-template disk pattern (PVE-18): an immutable
// (read-only) root plus a stateful models/cache volume, so model weights
// version independently from the runtime image.
type AITemplate struct {
	RootReadOnly bool
	ModelsSizeGB int
	ModelsLabel  string
}

// Validate gates AI templates: models volume is mandatory and sized.
func (t AITemplate) Validate() error {
	if t.ModelsSizeGB <= 0 {
		return fmt.Errorf("guestsetup: AI template needs a models volume size")
	}
	if t.ModelsLabel == "" {
		return fmt.Errorf("guestsetup: AI template needs a models volume label")
	}
	return nil
}

// FstabEntry renders the models-volume fstab line (nofail so a missing
// volume never blocks boot).
func (t AITemplate) FstabEntry() string {
	return fmt.Sprintf("LABEL=%s /models ext4 defaults,nofail 0 2\n", t.ModelsLabel)
}

// SupervisedService is one guest service directory (sv/ convention, OCM-28).
type SupervisedService struct {
	Name    string // e.g. authproxy, pty-server, gateway, filebrowser
	Command string // run command
}

// RunScript renders the service run file.
func (s SupervisedService) RunScript() string {
	return fmt.Sprintf("#!/bin/sh\nexec %s\n", s.Command)
}

// VersionsPin is the single version pin file content (versions.json).
type VersionsPin struct {
	Rootfs  string
	Runtime string
	Agent   string
}

// Render returns the pin file body.
func (v VersionsPin) Render() string {
	return fmt.Sprintf("{\n  \"rootfs\": %q,\n  \"runtime\": %q,\n  \"agent\": %q\n}\n",
		v.Rootfs, v.Runtime, v.Agent)
}
